[2025-10-20T18:48:43.121+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: global_earthquake_tsunami_risk_assessment.build_save_model manual__2025-10-20T18:48:39.645312+00:00 [queued]>
[2025-10-20T18:48:43.124+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: global_earthquake_tsunami_risk_assessment.build_save_model manual__2025-10-20T18:48:39.645312+00:00 [queued]>
[2025-10-20T18:48:43.124+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T18:48:43.124+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-10-20T18:48:43.124+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T18:48:43.129+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model> on 2025-10-20 18:48:39.645312+00:00
[2025-10-20T18:48:43.131+0000] {standard_task_runner.py:55} INFO - Started process 88 to run task
[2025-10-20T18:48:43.133+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'global_earthquake_tsunami_risk_assessment', 'build_save_model', 'manual__2025-10-20T18:48:39.645312+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpwqs8gl0x']
[2025-10-20T18:48:43.134+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask build_save_model
[2025-10-20T18:48:43.156+0000] {task_command.py:388} INFO - Running <TaskInstance: global_earthquake_tsunami_risk_assessment.build_save_model manual__2025-10-20T18:48:39.645312+00:00 [running]> on host a5e1af053224
[2025-10-20T18:48:43.190+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sreevarshan
AIRFLOW_CTX_DAG_ID=global_earthquake_tsunami_risk_assessment
AIRFLOW_CTX_TASK_ID=build_save_model
AIRFLOW_CTX_EXECUTION_DATE=2025-10-20T18:48:39.645312+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-20T18:48:39.645312+00:00
[2025-10-20T18:48:47.345+0000] {python.py:177} INFO - Done. Returned value was: [156764324.94559473, 100453288.90463684, 63079673.7039036, 52009749.864297196, 42276264.389006905, 36766117.74983503, 32494830.11681395, 28692270.335501783, 24842666.940346602, 21883740.442390844]
[2025-10-20T18:48:47.390+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=global_earthquake_tsunami_risk_assessment, task_id=build_save_model, execution_date=20251020T184839, start_date=20251020T184843, end_date=20251020T184847
[2025-10-20T18:48:47.409+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-10-20T18:48:47.420+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
